name: DevOps Project CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Super-Linter for Code Quality
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_NATURAL_LANGUAGE: false

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: |
          cd todo
          npm install
      - name: Run Tests
        run: |
          cd todo
          npm test -- --watchAll=false --passWithNoTests

  build_and_push_image:
    name: Build and Push Docker Image
    needs: [code, test]
    runs-on: ubuntu-latest
    
    # 1. إعطاء صلاحيات للخطوات
    permissions:
      contents: read
      id-token: write # <-- هذا مهم لإصدارات AWS SDK الحديثة (إذا احتجناه)
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # 2. خطوة تسجيل الدخول إلى AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 # <-- تأكد من أنها نفس منطقة ECR (يمكنك تغييرها إذا لزم الأمر)

      # 3. خطوة تسجيل الدخول إلى ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. خطوة بناء ورفع الصورة
      - name: Build and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-todo-app # <-- اسم المستودع الذي أنشأته في ECR
          IMAGE_TAG: ${{ github.sha }} # <-- استخدام رقم الـ commit كـ "وسم" فريد
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest